workflows:
  ios-workflow:
    name: Drop2Life iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          cd pwa

          xcodebuild -project Drop2Life.xcodeproj \
                     -scheme Drop2Life \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $HOME/build.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $HOME/build.xcarchive \
                     -exportOptionsPlist ../exportOptions.plist \
                     -exportPath $HOME/build
    artifacts:
      - build/*.ipa
